### ISSUE TITLE
Some DLA have z>z_QSO

### ISSUE THREAD

**Issue by londumas** [igmhub/LyaCoLoRe#22]
Some DLA have z_DLA > z_QSO
![distrib_zdla_m_zqso](https://user-images.githubusercontent.com/3166436/47573772-605e8c00-d8fb-11e8-98ed-974b108b8601.png)

**Comment by fjaviersanchez** [comment]
@alxogm I wonder if there's something going on when writing the file because the raw output from the DLA generation code explicitly prevents z_DLA > z_QSO, this is what I get when I run it with a toy QSO population:

![image](https://user-images.githubusercontent.com/13971732/47719195-b2c8e100-dc4a-11e8-8041-da964e08a640.png)

Could you please point me to the code that writes de DLA catalog `DLA.fits.gz`?

**Comment by jfarr03** [comment]
One thing I noticed on this issue: lines 177-179 seem to be commented out for some reason, and they explicitly revent z_DLA > z_QSO: 
   ```
 ##Only include DLAs where the DLA is at lower z than the QSO
    #DLA_Z_QSOs = object.Z_QSO[kskw]
    #DLA_table = DLA_table[DLA_table['Z_DLA']<DLA_Z_QSOs]
```
Is this the code you were referring to @fjaviersanchez or does this happen somewhere else?

**Comment by alxogm** [comment]
@fjaviersanchez 

Right now we are doing it in the Notebook Helion started.. we should move it to an script, I thought of merging it with the one I made to generate the catalog from the quick quasar output. 

https://github.com/igmhub/desi_QA/blob/master/Mocks/QA_DLA.ipynb

**Comment by fjaviersanchez** [comment]
Ok, I found the bug. In the notebook https://github.com/igmhub/desi_QA/blob/master/Mocks/QA_DLA.ipynb, in cell 11 you mask all the qso-related quantities with `w` except for `zqso`, so I would change this:
```
mockid = mockid[w]
frommockidtora = {mockid[i]:ra[i] for i in range(ra.size)}
```
To this:
```
mockid = mockid[w]
zqso = zqso[w]
frommockidtora = {mockid[i]:ra[i] for i in range(ra.size)}
```

After this fix the plot looks like this:

![image](https://user-images.githubusercontent.com/13971732/47733846-70fb6300-dc69-11e8-9ad9-6b56703f2b64.png)

Also, I would if the QSOs include RSD I would change this: `f_zdla = sp.append(f_zdla,h['DLA']['Z_DLA'][:])` to `f_zdla = sp.append(f_zdla,h['DLA']['Z_DLA'][:]+h['DLA']['DZ_DLA'][:])`

**Comment by londumas** [comment]
@fjaviersanchez, Thanks for finding the bug and sorry for making it.
However, I think that it would be better for DLA to be linke QSO: Z_RSD and Z_NO_RSD.
Would you agree?

**Comment by londumas** [comment]
Fixed. @fjaviersanchez You can close when you want to. 
![dv_dla_qso](https://user-images.githubusercontent.com/3166436/47735743-bd777c00-dc32-11e8-826f-30332aa6a194.png)

**Comment by fjaviersanchez** [comment]
@londumas Great plot! No worries! We have a bunch of bugs in our code that you helped us catch! Thanks a lot for your work checking these mocks. 

Yeah, I agree that having both Z_RSD and Z_NO_RSD would be even better. I don't know about what the best format to do so is. Probably, the most straightforward thing to do is to include a new column in the DLA files. I think that you are in a better position to decide what to do with this than I am so please, feel free to add it.

Since the issue with the DLA redshifts has been solved. I am closing this for now. Please, feel free to reopen it in case you find some other issues :)
