### ISSUE TITLE
n(z) mock random quasars distribution tails

### ISSUE THREAD

**Issue by londumas** [igmhub/LyaCoLoRe#83]
The high and low tails of the quasar distribution are different between mock quasars and random mock quasars.
 
![nz_all](https://user-images.githubusercontent.com/3166436/58810034-5364f200-85da-11e9-807f-c6e06b362290.png)

![nz_low_tail](https://user-images.githubusercontent.com/3166436/58810031-5364f200-85da-11e9-8770-2f867c8b69bf.png)

![nz_high_tail](https://user-images.githubusercontent.com/3166436/58810033-5364f200-85da-11e9-9e9e-c4a527b257b2.png)

**Comment by jfarr03** [comment]
@londumas this should be fixed in the latest version, which should replicate the shape of masterRSD exactly

**Comment by londumas** [comment]
Indeed, fixed. Thanks @jfarr03.
Can you also fix ticket https://github.com/igmhub/LyaCoLoRe/issues/85, then I will compute the auto-correlation and see if everything is good.
On a side note, could you tell me how you did the correction, so I can learn a bit? Also did you understand the `z=3.8`?

![low_z_tail](https://user-images.githubusercontent.com/3166436/58822159-10b01380-85f4-11e9-83db-26e3b0137b6d.png)

![high_z_tail](https://user-images.githubusercontent.com/3166436/58822160-10b01380-85f4-11e9-8d2e-ba6902380438.png)

**Comment by jfarr03** [comment]
No worries @londumas!

Basically it was because I was generating redshifts for the randoms from the input n(z) data file, whereas now the effective n(z) of the randoms is measured from the redshifts of the QSOs in the master file including RSDs.

At the low-z end, the QSOs in the mocks are cut hard at 1.8 in Z_QSO_NO_RSD. When you then add in RSDs, it makes the boundary fuzzy, whereas the randoms didn't have that before.

At the high-z, the issue was there because I had put in z=3.79 as a maximum value. I'm not quite sure why CoLoRe is generating QSOs above this redshift, but as the new method measures n(z) from the master file, it at least matches closely. 

Hope that makes sense!

**Comment by jfarr03** [comment]
And yes, I'll fix #85 shortly - I'm currently working on #84 so will finish that first!

**Comment by londumas** [comment]
@jfarr03, all sounds great. Thanks.
